# wrangler.toml
name = "properaccount"
compatibility_date = "2025-05-18"

# Avoid nodejs_compat flag when possible for better performance
# Only include it if you absolutely need Node.js APIs that aren't available in Workers
compatibility_flags = []

pages_build_output_dir = "./dist" # Standard for Astro projects deploying to Cloudflare Pages.

# [site] configuration can be useful if Wasm files are fetched from the root of dist.
# Astro typically serves from the `public` directory copied to `dist`.
# If Wasm files are placed in `public/mojo/`, they will be at `dist/mojo/`.
# If `Workspace('/mojo/loan-engine.wasm')` is used, ensure files are at `dist/mojo/loan-engine.wasm`.
[site]
bucket = "./dist"

# =========================================
# Production Environment Configuration
# =========================================
[env.production]
name = "properaccount-prod"
# Environment variables - values will be set through Cloudflare dashboard
# or using wrangler secrets for local development
vars = { ENVIRONMENT = "production" }

# --- Production D1 Database ---
[[env.production.d1_databases]]
binding = "DATABASE"
database_name = "properaccount-db-prod"
database_id = "bc1c31a7-957e-4086-aa55-54384fe0c80a" # Replace with your actual production D1 ID
migrations_dir = "cloudflare/d1/migrations"

# --- Production KV Namespaces ---
[[env.production.kv_namespaces]]
binding = "CONFIG_KV"
id = "d34d0bbafca1424d8c678aade9a60dce" # Replace with your actual production KV ID

[[env.production.kv_namespaces]]
binding = "REPORT_CACHE_KV"
id = "e1be52c7b89845c08dc30eb5f0af4562" # Replace with your actual production KV ID

[[env.production.kv_namespaces]]
binding = "SESSION_KV"
id = "ed0fcd9e4e26484ca2d299f47439c33d" # Replace with your actual production KV ID for sessions

# --- Production R2 Bucket ---
[[env.production.r2_buckets]]
binding = "DOCUMENTS_BUCKET"
bucket_name = "properaccount-documents-prod" # Replace with your actual production R2 bucket name

# --- Production Queues ---
# Uncomment when you're ready to use Queues
# [[env.production.queues.producers]]
# queue = "background-tasks-prod