# wrangler.toml
name = "properaccount"
compatibility_date = "2025-05-18"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "./dist"

[env.production]
name = "properaccount-prod"

[[env.production.d1_databases]]
binding = "DATABASE"
database_name = "properaccount-db-prod"
database_id = "bc1c31a7-957e-4086-aa55-54384fe0c80a"
migrations_dir = "src/cloudflare/d1/migrations"

[[env.production.kv_namespaces]]
binding = "CONFIG_KV"
id = "d34d0bbafca1424d8c678aade9a60dce"

[[env.production.kv_namespaces]]
binding = "REPORT_CACHE_KV"
id = "e1be52c7b89845c08dc30eb5f0af4562"

[[env.production.kv_namespaces]]
binding = "SESSION_KV"
id = "ed0fcd9e4e26484ca2d299f47439c33d"

[[env.production.r2_buckets]]
binding = "DOCUMENTS_BUCKET"
bucket_name = "properaccount-documents-prod"

[[env.production.queues.producers]]
queue = "background-tasks-prod"
binding = "BACKGROUND_TASKS_QUEUE"

# Default Bindings for local development
[[d1_databases]]
binding = "DATABASE"
database_name = "properaccount-db-dev"
database_id = "bc1c31a7-957e-4086-aa55-54384fe0c80a"
migrations_dir = "src/cloudflare/d1/migrations"

[[kv_namespaces]]
binding = "CONFIG_KV"
id = "d34d0bbafca1424d8c678aade9a60dce"

[[kv_namespaces]]
binding = "REPORT_CACHE_KV"
id = "local-report-cache-kv-placeholder"

[[kv_namespaces]]
binding = "SESSION_KV"
id = "local-session-kv-placeholder"

[[r2_buckets]]
binding = "DOCUMENTS_BUCKET"
bucket_name = "properaccount-documents-dev"

[[queues.producers]]
queue = "background-tasks-dev"
binding = "BACKGROUND_TASKS_QUEUE"

[dev]
ip = "127.0.0.1"
port = 8788
local_protocol = "http"