# .github/workflows/security-scan.yml
name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 5 * * 1' # Example: Run every Monday at 5:30 AM UTC

jobs:
  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required to upload CodeQL results
      actions: read # Required for private repositories if using CodeQL reusable workflows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Initializes the CodeQL tools for scanning.
      # Languages to scan are auto-detected.
      # You can customize languages if needed: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#configuring-options
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, typescript # Specify languages based on your project

      # Autobuild attempts to build any compiled languages (e.g., TypeScript).
      # If you have a custom build process for specific parts CodeQL needs to analyze,
      # you might need to add a build step here before `perform CodeQL Analysis`.
      # For Astro/Node.js projects, CodeQL often works well without explicit build commands here.
      # - name: Autobuild
      #   uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3